### ISSUE TITLE
How to receive translation with a variable in the client component

### ISSUE THREAD

**Issue by kaitok** [i18nexus/next-i18n-router#11]
Client component can take a translation as follows
```
<FormattedMessage id="greeting" />
```

But in my case need to pass translations to 3rd party component props such as
```
<LoadingOverlay spinner text={translatedText} />
```

I would like to use getIntl like the Server component, but the client component does not support async in Next.js.
```
const intl = await getIntl();
intl.formatMessage({ id: 'header' })
```

Is there a way to get the translation result in a variable in the client component?

**Comment by i18nexus** [comment]
Yes, you can use the `useIntl` hook provided by `react-intl`. This hook is an alternative to using the components. You can read about it in the [react-intl docs](https://formatjs.io/docs/react-intl/api).

```js
import { useIntl } from 'react-intl';

function LoadingComponent() {
  const { formatMessage } = useIntl();

  return (
    <LoadingOverlay spinner text={formatMessage({ id: "loadingMessage"})} />
  )
}

```

We'll probably end up changing our examples to use the `useIntl` hook instead of the `FormattedMessage` component.

**Comment by kaitok** [comment]
Thank you!
