### ISSUE TITLE
Feature: Allow omitting [lang] param from path

### ISSUE THREAD

**Issue by yellowchris** [i18nexus/next-i18n-router#2]
Is it possible to make it so that the `[lang]` path param can be omitted by default?

The language could maybe still be forced by optionally entering the `[lang]` param.
Or it could be disabled entirely and instead users could only change the language by triggering some API endpoint via the website UI that sets the requested cookie.

Thanks, great library otherwise. I think it should be built in Next.js.

**Comment by i18nexus** [comment]
Thanks for your feedback! The decision to use the `[lang]` path segment is due to SEO best practices. According to Google:

"Google recommends using different URLs for each language version of a page rather than using cookies or browser settings to adjust the content language on the page." [Source](https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites#use-different-urls-for-different-language-versions)

That being said, not every project requires SEO and it may be preferable not to have the locale in the path. So this is definitely something worth discussing. We'll keep this issue open for others to leave their comment.

**Comment by yellowchris** [comment]
I hear you, but in practice do the best SEO ranked sites really do this?

The vast majority of the top sites (including Google themselves) use subdomains or different tlds for this purpose. I would argue that it's rather unusual to see the language code in the path, I can't think of one major website that does it.

**Comment by i18nexus** [comment]
I meant to say that it would be poor SEO to use solely a cookie to change page content without changing the URL in any way. That's what I thought this issue was about. I don't mean to argue that the locale in the pathname is required for SEO, but just that the URL must be changed in some way for good SEO - whether that be through pathname, subdomain, or tld.

If your request is to be able to use this library with different subdomains or tlds per language, then this is something we definitely plan on getting to with this library!

In the meantime, we have been getting quite a few requests to not have the pathname prefix for the default language. This should be released by next week. The language will still appear in the pathname for non-default languages though.

**Comment by i18nexus** [comment]
We're going to close this since the version 3.0.0 allows you to no longer include the language in the pathname for the default language. If this doesn't solve what you're looking for, please feel free to create a new issue describing what specific feature you're looking for.

**Comment by DavidRouyer** [comment]
@i18nexus
I'm building a dashboard and I don't need to have the language in the pathname at all.
Could you add an option to disable the prefix entirely please?

**Comment by i18nexus** [comment]
Hi @DavidRouyer !

If you want solely cookie based internationalization, it should be rather trivial to implement without this package. The vast majority of this package would go unused.

All you would need to do is set a `locale` cookie in your middleware based on the request's `accept-language` header. In the case a user want's to change their language, you would just set the cookie when their selected the language. That's all the would be needed for your implementation.

If we get more request's about this we'd be happy to implement. But from a developer perspective, it seems like installing a package to essentially set a cookie would be overkill.

**Comment by DavidRouyer** [comment]
Thanks a lot!

I made a solution based on your code!

`middleware.ts`:

```ts
export function middleware(request: NextRequest) {
  const { defaultLocale, locales, localeCookie = 'NEXT_LOCALE' } = i18nConfig;

  let locale;
  if (localeCookie) {
    const cookieValue = request.cookies.get(localeCookie)?.value;

    if (cookieValue && locales.includes(cookieValue)) {
      locale = cookieValue;
    }
  }

  if (!locale) {
    locale = localeDetector(request, i18nConfig);
  }

  if (!locales.includes(locale)) {
    console.warn(
      'The localeDetector callback must return a locale included in your locales array. Reverting to using defaultLocale.'
    );

    locale = defaultLocale;
  }

  const response = NextResponse.next();

  response.cookies.set(localeCookie, locale);

  return response;
}
```

`currentLocale.ts`:
```ts
const currentLocale = (): string => {
  const { defaultLocale, localeCookie = 'NEXT_LOCALE' } = i18nConfig;
  return cookies().get(localeCookie)?.value ?? defaultLocale;
};

export default currentLocale;
```

I'm using `react-intl` so I don't need `useCurrentLocale` anymore, I can use: `const { locale } = useIntl();`

**Comment by i18nexus** [comment]
@DavidRouyer Thanks for sharing! Yes, the `useCurrentLocale` hook is actually probably not needed with `react-intl` since the locale is available using the `useIntl` hook.

**Comment by i18nexus** [comment]
Just wanted to provide an update here that this is now supported using the `noPrefix` config option in v5.4.0!
