### ISSUE TITLE
Not working when click on browser back button

### ISSUE THREAD

**Issue by iEricKoh** [i18nexus/next-i18n-router#22]
I tried the example from this repo, after I switched to a new lanuage let's say `de`, and then pressed on browser back button, it's still stay on `de`.

Let's say I naviagted from `en` to `de`, I expected i can view the page in `en` after i press back button.

**Comment by i18nexus** [comment]
When the "NEXT_LOCALE" cookie is set and you visit a base path without a locale prefix, you will be redirected to the language path of the cookie. The dropdown in the example is setting the cookie to "de". Hitting the back button is going to a base path and therefore redirecting because of the cookie.

If this back button behavior is important to you, you have a couple options:

1. Do not use the locale cookie, and instead include the locale in the `href` of your link tags:
`<Link href={`/${locale}/about`} />`
2. You can set `prefixDefault` to `false`. This will cause the language prefix to always be in the pathname and not need to read the cookie.

Otherwise we're open to reviewing a PR if you have ideas on how to make the back button work with the cookie.

**Comment by i18nexus** [comment]
Closing - This behavior is to be expected when setting a cookie. Cookie usage is optional and other strategies (listed above) are available to achieve changing the language when clicking the back button.
