### ISSUE TITLE
change the locale in the path url manually

### ISSUE THREAD

**Issue by Broshnitskiy** [i18nexus/next-i18n-router#28]
**Hello,**
 I set prefixDefault false in the settings. I change languages using your example document.cookie = `NEXT_LOCALE=${newLocale};expires=${expires};path=/`;
In this way, my locale is stored in cookies. But after that I can't manually change the language in the url, it takes me back to the language in cookies, if I enter the default language or "/". 
Is it way to make it possible to control the language with url, and not only with buttons? 
And next moment, I can change the language with the buttons only by setting the cookie = `NEXT_LOCALE"=${newLocale} (like in your example), and why can't I change the language through the next-link "/en" and "/", but only through a cookie?

**Comment by i18nexus** [comment]
Hi there! I happen to be online as you submitted this 🙂

If you go to a url without a locale (for example "/"), this causes the next-i18n-router to check if there is a locale cookie. If there is, it will redirect to that locale. If there is no cookie, it will use the localeDetector to detect the user's browser locale and then redirect to that locale.

It sounds like you would like to be able to manually enter "/de" (for example), and then click a link with `href="/about"` and be directed to "/de/about" without setting a cookie. Instead of just routing to "/about" as it does today.

We thought about this. But we really couldn't think of a real world scenario where this would be useful. As an English speaker, if someone provides me a link to your website at "/de" and then I click a link on the page to "/about" and it directs me to "/about" I would be happy. Because why would I not want to view the page in my own language? If I did prefer German, the "/about" link would be redirected to "/de/about" based on request headers anyway. 

Now that you understand our thinking here, we would be happy to hear out your use case. In what case would you prefer someone click a link and not be redirected to their preferred language?

**Comment by Broshnitskiy** [comment]
I understand your approach)
I meant something otherwise: I have "uk" locale in my cookies or empty cookies, I want to manually write "/en" in the url (it is default locale with prefixDefault | false), then press enter and have this "en" value  also change in cookies automatically, instead now I am redirected to "/uk" even though I don't want it.

And my second question was that I can't change the language with simple <Link href="/uk">/uk</Link> or router.push("/uk") without this record: document.cookie = `NEXT_LOCALE=${newLocale}.

**Comment by i18nexus** [comment]
**Question 1:**

What is happening today is: 
"/en" redirects to "/" and then "/" redirects to "/[cookie]" or "/[browser language]"

When prefixDefault is false, "/[defaultLocale]" redirects to "/".

So it sounds like you would prefer that the cookie automatically change whenever a new language is visited, rather than forcing developers to set the cookie themselves? So simply navigating to "/de" will set NEXT_LOCALE to "de" and navigating to "/en" will set NEXT_LOCALE to "en"?

I can see this being useful I suppose. Perhaps we can make it a config option.

**Question 2:**

You should be able to visit "/uk" regardless of what the cookie is set to. The only time the cookie is read is when you visit a path without a locale. Simply routing to "/uk" isn't going to change the cookie though. Clicking a link with `href="/about"` on the page will still direct you to "/about", not "/uk/about". So it sounds like this is basically the same question as above, correct?

**Comment by Broshnitskiy** [comment]
thanks for the accessible explanation of how your middleware works

Regarding your answer about site navigation, I write like this <Link href={`/${lang}/clients`}> and I don't bother to constantly jerk the language of the browser.

Regarding Question 2: Why doesn't this code work for me without saving it in cookies?
` const handleChange = (e) => {
    const newLocale = e.currentTarget.dataset.language;

    if (
      currentLocale === i18nConfig.defaultLocale &&
      !i18nConfig.prefixDefault
    ) {
      router.push("/" + newLocale + currentPathname);
    } else {
      router.push(
        currentPathname.replace(`/${currentLocale}`, `/${newLocale}`)
      );
    }

    router.refresh();
  };
  
   <li>
        <button
          onClick={handleChange}
          type="button"
          data-language="uk"
        >
          UA
        </button>
      </li>
      
      <li>
        <button
          onClick={handleChange}
          type="button"
          data-language="en"
        >
          EN
        </button>
      </li>`

**Comment by i18nexus** [comment]
I think we'll make a config option to automatically update the cookie when navigating to a new language.

Regarding your code, I'll have to test it when I have time next week. It looks ok to me. Can you double check the path being routed to by console logging it in the handleChange conditional? If the path looks ok, can you try removing router.refresh and see if that does anything? Lastly, can you tell me what you are experiencing?

**Comment by Broshnitskiy** [comment]
```
const i18nConfig = {
  locales: ["uk", "en"],
  defaultLocale: "en",
  routingStrategy: "dynamicSegment",
  prefixDefault: false,
};
export default i18nConfig;
```
```
 const handleChange = (e) => {
    const newLocale = e.currentTarget.dataset.language;

   
    console.log(currentLocale); // "uk"
    console.log(newLocale); //  "en"
    console.log(currentPathname); // "/uk"
    console.log(currentPathname.replace(`/${currentLocale}`, `/${newLocale}`))
    if (
      currentLocale === i18nConfig.defaultLocale &&
      !i18nConfig.prefixDefault
    ) {
      router.push("/" + newLocale + currentPathname);
    } else {
      router.push(
        currentPathname.replace(`/${currentLocale}`, `/${newLocale}`)
      );
    }

    // router.refresh();
  };
```



**About experiencing:** I am writing a web application for the company) and the task is to make the default English language on the root ("/") without a redirect at first boot, and to take the browser language into account during the initial download. Your library allows me to hide the default language, but I understand that redirection still happens in middleware through rewrite.

**Comment by i18nexus** [comment]
Sorry not sure how this issue slipped through the cracks.

We've tested your above code and it works as intended. The page is being redirected to the correct locale. But of course it's not going to persist the locale on the next link click because there is no cookie set. We are using the latest version (v5.0.2) so maybe try updating and see if that helps anything.

**Comment by Broshnitskiy** [comment]
the problem is not in the version!

the problem is that: if the defaultLocale is not equal to the language in the browser, then you cannot change the language using the buttons. For example, my language in the browser is "de", and defaultLocale in config: "en". I go to the site and it is displayed in the "de" language (because the browser is like that), then I switch the language to "en" (defaultLocale and prefixDefault: false) and the middleware is triggered, which does not redirect me to the English language, but again to in German because it is in the browser.

if defaultLocale is equal to the language in the browser, then there is no such problem and everything works properly

**Comment by i18nexus** [comment]
I see. Your problem is that /en redirects to / which redirects to /de. One solution is to set `localeDetector: false` in your config. This will prevent / from redirecting to /de. But it sounds like you do want locale detection. If you want locale detection, the only way to handle it is to set a cookie on language change like in our examples.

These are currently the 2 possible solutions to your problem. But if you can't use cookies and you require locale detection, then neither of these solutions will work for you. In which case, I'm not sure what can be done. I'll need to know more about what you're trying to accomplish. Why you are unable to use cookies and why can't you turn off locale detection? Can you give me more insight into your requirements?

**Comment by i18nexus** [comment]
Marking as stale

**Comment by Broshnitskiy** [comment]
> I see. Your problem is that /en redirects to / which redirects to /de. One solution is to set `localeDetector: false` in your config. This will prevent / from redirecting to /de. But it sounds like you do want locale detection. If you want locale detection, the only way to handle it is to set a cookie on language change like in our examples.
> 
> These are currently the 2 possible solutions to your problem. But if you can't use cookies and you require locale detection, then neither of these solutions will work for you. In which case, I'm not sure what can be done. I'll need to know more about what you're trying to accomplish. Why you are unable to use cookies and why can't you turn off locale detection? Can you give me more insight into your requirements?

Yes, I used cookies to solve this problem. there is no other way. thanks for the clarification
