### ISSUE TITLE
Usage with App and Pages Routers working together

### ISSUE THREAD

**Issue by k-bialucha** [i18nexus/next-i18n-router#38]
I have an app with the classic Pages Router, where I'm trying to introduce App Router now. It's configured to work with the default i18n config from Next. Despite trying various approaches, I haven't found a good method to handle localized paths for both routers at the same time. One workaround that seems functional involves using fully custom rewrites/redirects in the middleware (without `next-i18n-router` and Next's i18n), but I find this less than ideal.

My questions would be:
1. Is it possible for `next-i18n-router` to work in apps that have both routers enabled?
2. If it is, can you provide an example?

**Comment by i18nexus** [comment]
This library was designed specifically for the App Router and has not been designed or tested to work in tandem with the Pages Router. 

As far as localizing paths, the most straightforward way would be to use rewrites in your next.config.js.

For example:
```
module.exports = {
  async rewrites() {
    return [
      {
        source: '/es/hola-mundo',
        destination: '/es/hello-world'
      },
    ]
  },
}
```

But the problem here is that /es/hello-world will still be accessible. Ideally /es/hello-world should return a 404 or redirect to /es/hola-mundo. The other problem is it becomes complicated to use the `<Link />` component when every language has its own localized pathname.

**We have decided we're going to implement a new feature in this library to make pathname localization easier. This new feature will allow for developers to provide a map of localized pathnames to be passed into the `i18nRouter` middleware.**

This is currently our top development priority on this package so hopefully we can get something out by the end of the week. Thanks for your feedback!

**Comment by k-bialucha** [comment]
Thanks for answering @i18nexus!

Maybe it was not clearly stated, but I don't even need to support fully translated path names (but also this is great you're going to support it!).

I only need a page to be accessible under both `/en/hello-world` and `/es/hello-world` and I need to be able to detect on what locale I'm currently at. So the tricky part is that it needs to work on both Next's Routers - and I couldn't make it work with Pages Router, unfortunately.

As mentioned, I went with a custom solution, and I developed more or less the following logic:
```typescript
type RoutingResult = {
  type: "redirect" | "rewrite",
  url: URL
} | null;
// simplified:
function getRouting(pathanme: string, basePath: string, cookieValue: string): RoutingResult {
  // some logic
}
// usage - in middleware
const routing = getResult("/es", "http://example.com", "fr")
if (routing?.type === "redirect") {
  return NextResponse.redirect(routing.url);
}
```
Note: I also had to remove `i18n` section from `next.config.js`.

This way I think it's more flexible and can combine it with other logic existing in my middleware. With your `i18nRouter` function it was harder, because it was like a "black box" which was doing something I didn't really understand (until checking the source code). Feel free to get inspired by it :slightly_smiling_face:

**Comment by i18nexus** [comment]
Thanks for sharing! Sorry I misunderstood that you wanted pathname localization. I'll have to create a new issue for that now 🙂

In the meantime, we don't plan on handling Pages Router implementations with this library. So I'm going to close this issue for now. If more people bring it up we'll look into this deeper. Thanks for sharing your solution though.
