### ISSUE TITLE
question: do i have to use async in every page in order for translation to work with i18n next????

### ISSUE THREAD

**Issue by zakidze** [i18nexus/next-i18n-router#40]

**Comment by zakidze** [comment]
an example :
in the example you provided you use async also , server component dosent work,  must use use client and have to wrap all the pages in provider

**Comment by i18nexus** [comment]
I'm not entirely sure what you're asking and which tutorial you're referring to. But I'll do my best!

Each page needs to be an async server component. The component needs to be able to load your translations from JSON which is an asynchronous task. If you're saying that you want your page to be a client component, then the strategy shown in our examples will not work. It's a simple fix for you though. All you need to do is nest your current page in a client component and leave the page component as a Server Component. For example, in the i18next example:

```
const i18nNamespaces = ['about', 'test'];

async function Page({ params: { locale } }: { params: { locale: string } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <TranslationsProvider
      namespaces={i18nNamespaces}
      locale={locale}
      resources={resources}>
      <YourCurrentClientComponentPage />
    </TranslationsProvider>
  );
}

export default Page;
```

**Comment by zakidze** [comment]
Thank you answered my question, that what I was looking for the tutorial I was referring to is the "[i18next-example](https://github.com/i18nexus/next-i18n-router/tree/main/examples/i18next-example)"    on this repo

 now  my second question is :  how about a server page, and inside it a server component how to load the translations to server component (not page)

**Comment by zakidze** [comment]
for second question: const { t } = await initTranslations(locale, i18nNamespaces);  this requires local , is there a way to get the local without  passing it as prop in any component even deeply nested

**Comment by i18nexus** [comment]
Unfortunately this is an issue with Next.js App Router in general where prop-drilling is required in order to pass page params down through Server Components. There are 2 potential solutions:

1. This library sets a header called `'x-next-i18n-router-locale'`. You can read that header in your server component to get the current locale. **BUT** I would not recommend this because reading headers prevents use of SSG in Next. In other words, you are not able to use `generateStaticProps` if you do this.
2. There are several discussions about this issue. One library I see that is recommended for passing data through Server Components is this one: https://www.npmjs.com/package/server-only-context. It allows you to create a server "context" similar to `useContext` in Client Components. You could use this library to create a locale context on your server. **I have not tested this library** and it is not used very much judging by the number of Github stars. But we have plans to look into this strategy to integrate it into this library.

**Comment by zakidze** [comment]
how about getting the local directly from the cookie? can i count on that ? read the cookie server side i think its possible to read it at any component but is it like robust solutions?
whats your opinion
for me generateStaticProps  is a must

**Comment by i18nexus** [comment]
I'm pretty sure that reading cookies in a server component has the same problem as reading headers. It won't let you use generateStaticProps. You can test by running `npm run build` and seeing if you get an error with generateStaticProps.

**Comment by zakidze** [comment]
to my suprise  : it did work fine  just test it  here what i used  i m right now just tryed it im not sure if its luck 



import { cookies } from 'next/headers';


export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

**Comment by zakidze** [comment]
by the way there are alot of typescript errors in i18n.ts

**Comment by zakidze** [comment]
![Capture](https://github.com/i18nexus/next-i18n-router/assets/61497110/9d280d56-4c1d-4c6f-9ce0-5d7eede6d133)
 you can see here that it works even changing the local does change the cookeis and you see it even the production server

**Comment by i18nexus** [comment]
A problem with using cookies though is that the cookie will not be set on first load. The cookie is set client side. So the initial rendering of the server component will have no cookie. Only on subsequent requests.

**Comment by i18nexus** [comment]
I'm going to close this because we've really moved off of the topic of the original purpose of this issue. For future, if you have questions about implementation please reach out to support@i18nexus.com. Our support is available not only for our product, but also for next-i18n-router in general. You can also message us through the in-app chat at i18nexus.com.  We would like to keep the Github issues for reporting any problems or feature requests for this library. Thanks! 🙂
