### ISSUE TITLE
A weird behavior after changing the locales or updating the default local in i18n config

### ISSUE THREAD

**Issue by zakidze** [i18nexus/next-i18n-router#41]
After changing default local in the i18n config or even changing locales , a weird behavior appears like the default local don't work anymore and redirect to the old default local

a reproduction : just play with the example provided in this repo i18nnext change the local write-in URL localhost:3000/de , try to play with those, and you see a weird behavior

**Comment by i18nexus** [comment]
Someone else asked about this in an email to us, so I'll paste our response here:

This is likely due to the fact that your defaultLocale is different from your browser locale. The locale detection done in the next-i18n-router middleware is automatically redirecting you to your preferred language based on your browser settings.

Any time a path is visited that does not contain a locale, next-i18n-router uses its locale detector logic to redirect you to your preferred language.

Let's say your defaultLocale is "ja" and your browser language is "en":
“/ja” redirects to “/“ which therefore redirects to “/en”.

This is expected behavior. If you want to view your app in Japanese, you should set the NEXT_LOCALE cookie to “ja”. If you view our tutorial, we have a LanguageChanger component that does exactly this. Using the visitor’s browser language is the best default. But if you want the visitor to be able to view another language, you should handle that with a dropdown that sets a cookie. The cookie overrides the automatic language detection.

**Comment by zakidze** [comment]
is there a way to completly hides the local? in the url??????

**Comment by i18nexus** [comment]
> is there a way to completly hides the local? in the url??????

No there is not a way to completely hide the locale. Please see this issue if you want to implement that: https://github.com/i18nexus/next-i18n-router/issues/2

> i want the local that user typed in adressBar and if it was included in my [i18n locales] set a cookie and next time it will goes to that local (like making the adress bar a launguage switcher) , else , go to default local or continue execution normaly

To do this, I would create a client component that sits inside of your root layout. The component would have logic to set the cookie when the layout is rendered.

**Comment by zakidze** [comment]
That's genius, thank you so much
