### ISSUE TITLE
Infinite redirect loop if not using default locale

### ISSUE THREAD

**Issue by Alexnortung** [i18nexus/next-i18n-router#45]
The following code creates an infinite redirect loop if your locale is not the default locale.

For example: the default locale is `en`  and my locale is `da`, then this if statement will redirect me again since my locale is not the default locale

https://github.com/i18nexus/next-i18n-router/blob/acd6fff344f355839e733003c55bd7eae9e196cc/src/i18nRouter.ts#L78-L81

**Comment by i18nexus** [comment]
This code is only reached when there is no locale present in the pathname. This code redirects to a pathname that includes a locale, so it will not be run again.

Are you experiencing an infinite loop? If so, can you provide your config and the pathname that leads to the loop?

**Comment by Alexnortung** [comment]
Yes I did experience an infinite redirect loop. I had a very basic config, basically the same as the [example usage](https://github.com/i18nexus/next-i18n-router#example-usage), but with `locales: ['da','en']`

**Comment by Alexnortung** [comment]
I tried setting it up again, but I cannot reproduce it either.

**Comment by i18nexus** [comment]
One other thing I want to mention. If you're using `--turbo` for Turbopack, there are known issues as can be seen here: https://github.com/i18nexus/next-i18n-router/issues/44

Not specifically a bug with this library, but turbo is still in beta and has issues with middleware redirects. Infinite loops are one issue that seems to occur with Turbopack. So I recommend not using `--turbo`.

**Comment by pmoeugene** [comment]
We've also bumped into an infinite redirect loop case, but it was very tricky to catch-reproduce-fix, so I'd like to share our observations for traceability.

Context:
We have a podcasts/audiobooks app, and a Next.js v15.3.3 app router website with overview of which exclusive shows we have, some payment plans info, static pages, yada yada... Show pages support both `/shows/{show_name}` and `/{region}/shows/{show_name}` variations, and will show you the info of the show and some region-specific payment plan stuff based on the region if present. Global version just shows the podcast/audiobook info, and some defaults.

Steps to reproduce:
1. Enter the website through one of the regions we support, so that the `NEXT_LOCALE` cookie is now assigned a value (e.g. `no` for Norway). 
2. Google search for any available show page on the website. You will be presented with `/shows/{show_name}` links 90% of the times, if the show is not region-unique.
3. Navigate to the show page w/o the region in URL.
4. When user lands on the show page, it starts infinitely redirecting between `/shows/{show_name}` and `/{region}/shows/{show_name}`. The `NEXT_LOCALE` cookie has `no` region from point 1.

I've ~banged my head on the table~ started debugging/comparing/logging when is the locale being set when user enters the website, checking the root middleware, etc. Then I've compared the headers when user lands on the show page via direct navigation vs from google search and found out that `NEXT_LOCALE` cookie is not present in the request headers for the initial Doc page fetch. That was because of `SameSite 'Strict'` setting of the cookie, which doesn't expose it outside when requesting the page, only from inside the domain.

As soon as I added `cookieOptions: { sameSite: 'Lax' }` to the `i18nConfig`, it worked like a charm, with no ability to reproduce the infinite redirect loop again.

Please consider defaulting to `sameSite: 'Lax'` cookie setting or provide a bit more context regarding the choice of defaulting to `'Strict'` in the first place. Thanks!
