### ISSUE TITLE
defaultLocale not working

### ISSUE THREAD

**Issue by sajjadramezani73** [i18nexus/next-i18n-router#48]
hi
I have used this package in the next 13.4 app router project

config for i18n with persian and turkey and english language and defaulLocale equal fa
const i18nConfig: Config = {
  locales: ['fa', 'tr', 'en'],
  defaultLocale: 'fa',
  prefixDefault: true,
};

why after the implementation of the project
localhost:4200/en it opens?

**Comment by i18nexus** [comment]
Hi! This is probably because your browser language is set to English. The `i18nRouter` function in your middleware redirects visitors to their preferred language based on the `accept-language` header on the request. If your browser language is not set to English, please check that you do not accidentally have the NEXT_LOCALE cookie set.

This is expected behavior is your browser language is English. If you don't want automatic locale detection, you can change the `localeDetector` config option to `false`.

**Comment by sajjadramezani73** [comment]
Thank you
This item worked

**Comment by i18nexus** [comment]
Great!

**Comment by Lighttree** [comment]
Hi, I have a question regarding the same topic, so just not to open a new ticket.

**Comment by Lighttree** [comment]
Hi, I have a question regarding the same topic, so just not to open a new ticket.

I'm trying to implement localization for `output: "export"` based on `SSG` section from this tutorial: https://i18nexus.com/tutorials/nextjs/react-intl

**Comment by Lighttree** [comment]
@i18nexus Isn't it working, but with the same limitations that are described here: https://next-intl-docs.vercel.app/docs/routing/middleware#usage-without-middleware-static-export ? I mean I'm able to get the correct build. Maybe I'm missing something.

**Comment by i18nexus** [comment]
@Lighttree It looks like it will build, but when running `npm run dev` you will see an error.

If you were to use this library with `output: 'export'`:

1. Just like in the next-intl docs you provided, you will need to make sure `prefixDefault` is set to `true`. Since we can't use rewrites, the locale always has to be present in the pathname.
2. Locale detection will not work since that's run in the middleware.
3. Just like in the next-intl docs you provided, you will need to create a page for your base path that redirects to `/en` (or whatever your default locale is) or else `/` will return a 404.

If you do the 3 things above, you might as well uninstall this library because it won't be doing anything at all. You just need `react-intl` and the `[locale]` dynamic segment.

This being said, it is worth us taking a look at how we can support `output: 'export'`. I'm guessing it would look something like having a script that runs before build that copies the contents of the `[locale]` directory into `app`. Other changes would obviously have to be made, but I think that would be the basic strategy.
