### ISSUE TITLE
Middleware with Supabase

### ISSUE THREAD

**Issue by meetyan** [i18nexus/next-i18n-router#56]
Hey there,

Just wondering how I can use `next-i18n-router` with `@supabase/ssr` in middleware.ts?

I am following the [supabase tutorial](https://supabase.com/docs/guides/auth/server-side/nextjs) to create a Nextjs app. However, in section 4 `Hook up middleware`, it seems hard to return `i18nRouter` as the middleware returns a `NextResponse`:

```js
export async function middleware(request: NextRequest) {
  let response = NextResponse.next({
    request: {
      headers: request.headers,
    },
  })

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value,
            ...options,
          })
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          })
          response.cookies.set({
            name,
            value,
            ...options,
          })
        },
        remove(name: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value: '',
            ...options,
          })
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          })
          response.cookies.set({
            name,
            value: '',
            ...options,
          })
        },
      },
    }
  )

  await supabase.auth.getUser()

  return response
}
``` 

Could you please demonstrate how to properly adjust the code with these two libraries?

Thank you!

**Comment by meetyan** [comment]
Thank you so much. After testing for a day, it seems to work fine!

I have another question: when adding `i18nRouter` to middleware.ts, everything becomes a bit slower.

Previously, when the app was deployed to Vercel, switching between routes was instant. Now it takes like one to two seconds more to load.

Is it because `i18nRouter` has to detect the locale every time and redirect to the right route?

**Comment by i18nexus** [comment]
It shouldn't be slower to switch between routes. It's hard to say what the issue could be. I'd put a log in your middleware to see how many times the middleware is being run on page change. Maybe there's a loop being caused by the supabase/i18nRouter combination.

You actually don't need to add the locale prefix to every Link. The middleware will automatically redirect to the current locale's route. But for SEO purposes, it is better to have the locale in the href of the Link. In that case, you could simply create a helper function or a <LocaleLink /> component that automatically prepends the locale to all hrefs.

**Comment by i18nexus** [comment]
Stale
