### ISSUE TITLE
Support localStorage

### ISSUE THREAD

**Issue by monolithed** [i18nexus/next-i18n-router#62]
It's important to support localStorage 'cause implementing through cookies requires writing a privacy policy and implementing a mechanism for obtaining consent to use cookies and their processing (GDPR).

**Comment by i18nexus** [comment]
If you want to use localStorage, that's possible. Just set the `serverSetCookie` option to `never`. If you have a language selector component like in our examples, you just need to have it set the current language in localStorage instead of setting a cookie. You would also need to make sure to prefix the current locale on all `href`s in `Link`s throughout your app.
