### ISSUE TITLE
Using periods on the root path segment does not return 404

### ISSUE THREAD

**Issue by GAsplund** [i18nexus/next-i18n-router#78]
For example, navigating to `/this.does.not.exist` will redirect to the / route using the default locale instead of showing a 404. However, doing the same on any other path (e.g. `/settings/this.does.not.exist`) will yield a 404 error as expected.

My config:
```js
const i18nConfig: Config = {
  locales: ['sv', 'en'],
  defaultLocale: 'sv'
};
```

**Comment by i18nexus** [comment]
Hi there. The reason this is occurring is because `/this.does.not.exist` bypasses the middleware. If you copied the middleware config from our documentation, your config likely looks like this:

```
export const config = {
  matcher: '/((?!api|static|.*\\..*|_next).*)'
};
```

The `.*\\..*` part of the regex causes any requests with a period to bypass the middleware. This portion of the regex exists because we don't want to run middleware on files in the public folder. It's kind of a catch-all for any file with an extension, like "image.png".

This may not be ideal, but this was the best solution at the time of building the library. I'm curious to see if there have been any developments in Next.js to make this matcher config better.

In the meantime, you have 2 options:
1) Change the regex to include more specific extension names that are contained in your public folder. 
2) In your layout.js, put a conditional at the top of your component that checks if the pathname contains periods, and if so call `notFound`. 

If anyone has any suggestions for a better middleware matcher config that bypasses public files, please let us know.

**Comment by GAsplund** [comment]
Thank you for the detailed response! Yes, I did copy the matcher from the example config. The best solution for us was to use layout.ts and return a custom 404 component instead of inserting child elements.

I am not sure if I should keep this issue open since it is technically related to what this application does while also being out of your hands. I will however leave that up to you. That said, having some documentation on this would probably not be a bad idea.

**Comment by i18nexus** [comment]
Sounds good. We'll close this for now, until Next.js provides a better way to only run middleware on page routes.
