### ISSUE TITLE
redirect status code is 200

### ISSUE THREAD

**Issue by rezamirzapour** [i18nexus/next-i18n-router#90]
when you sue redirect fucntion that is imported from "next/navigation", the status code will be 200.

here is an example: 

import { redirect } from "next/navigation";
export default function Home() {
  redirect("/about-us");
}

when you don't use next-i18n-router and use redirect function, nextjs gives you 307 status code while using next-i18n-router changes the status code to 200

**Comment by i18nexus** [comment]
This seems to be due to our usage of rewrites in the middleware. `/about-us` is rewritten from `/[defaultLocale]/about-us`. There is an open issue for NextJS about this behavior here: https://github.com/vercel/next.js/issues/50155

If this is a problem for you, perhaps in the meantime you can include the current locale:

`redirect("${currentLocale}/about-us")`

This will cause a redirect to `/about-us`.

But unfortunately this isn't something we can control on our end.

**Comment by i18nexus** [comment]
We'll track the aforementioned issue on the nextjs repo, but I'm going to close this issue for now since there's nothing we can do until it's fixed within Next
