### ISSUE TITLE
Handling language-based slugs for pages

### ISSUE THREAD

**Issue by zensitively** [i18nexus/next-i18n-router#98]
The guide correctly states that the default behavior is:

```
English: /products
German: /de/products
```

However, nobody in the world would want to use /de/products as a slug. It should be `/products` and `/de/produkte` (German word for products).

But there doesn't seem to be a way to translate the slug of individual pages - perhaps the most crucial feature of any i18n router.

Is that possible with next-i18n-router?

**Comment by i18nexus** [comment]
Hi there! We do not have a built in option for this. But it can be easily done by setting rewrites in your next.config.ts.

For example:

```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: '/de/produkte',
        destination: '/de/products'
      }
    ];
  },
  async redirects() {
    return [
      {
        source: '/de/products',
        destination: '/de/produkte',
        permanent: true
      }
    ];
  }
};

module.exports = nextConfig;
```

Presumably you would have a map of all languages with their respective pathnames and dynamically populate the `rewrites` and `redirects` arrays.

The redirect really is optional. I added it because if somehow someone got to the pathname `/de/products`, we'd rather them view it on the `/de/produkte` pathname. Ideally your `link` tags should have the correct translation dynamically populated in the href to avoid always redirecting on every link click in a non-default language.

It would probably make most sense to return a 404 on `/de/products` though. This is possible, but more complicated. If you want to do this, you would remove the `redirects()` from your nextConfig above (but leave the `rewrites()`. Then you would do something like this in your middleware:

```js
export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // presumably use your pathnames map used in nextConfig to dynamically generate these conditions in a loop
  if (pathname === '/de/products') {
    return NextResponse.rewrite(new URL('/de/not-found', request.url));
  }

  return i18nRouter(request, i18nConfig);
}
```

This will return a 404 when someone tries to go to `/de/products`. Funny thing is that `'/de/not-found'` could be anything. You could put it as `'/de/asdfghhjj'` too. The point is we're just trying to rewrite with a not-found response, so the page you're rewriting with cannot exist. I wish there were a less weird way to implement a not-found rewrite in the middleware, but this seems to be the working solution.

This 404 implementation gets complicated when you have more complex pathnames like `/de/products/:id/prices/:priceId`. In the middleware's conditionals, you will have to use a Regex to parse out the dynamic segments instead of using a simple `===` against the pathname as we do above.

With this all being said, it probably makes sense that this library have configuration options for translated pathnames, so that users of this library don't have to do the complicated pathname matching in the middleware as I just mentioned. However, if using redirects instead of 404's is acceptable, then implementing this should be trivial and not as needed of a feature for this library.

We're certainly open for feedback on this and we're interested in the best way to implement this in this library if needed.

**Comment by i18nexus** [comment]
I'm going to close this issue since I've explained how to implement this. But if others would like us to have a built-in solution for this, please comment on this issue and we'll re-open it. Any further discussion also welcomed here.
